# Generated by Django 3.2 on 2025-09-16 21:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mid', models.CharField(max_length=60)),
                ('isTyping', models.CharField(default=0, max_length=3)),
                ('messType', models.CharField(default=0, max_length=3)),
                ('rec_status', models.CharField(default=0, max_length=3)),
                ('snd_status', models.CharField(default=0, max_length=3)),
                ('rec_usr', models.CharField(max_length=60, null=True)),
                ('snd_usr', models.CharField(max_length=60, null=True)),
                ('conv_id', models.CharField(max_length=60, null=True)),
                ('message', models.TextField(null=True)),
                ('messStat', models.CharField(default=0, max_length=3)),
                ('lastOnline', models.CharField(max_length=60, null=True)),
                ('sent_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Infor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60, null=True)),
                ('desc', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedLessons',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instructor', models.CharField(max_length=60)),
                ('student', models.CharField(max_length=60)),
                ('assign_id', models.CharField(default=login.models.gen16, max_length=60)),
                ('descript', models.TextField(null=True)),
                ('lesson_date', models.CharField(max_length=20, null=True)),
                ('lesson_time', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(default=0, max_length=3, null=True)),
                ('added_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
