# Generated by Django 3.2 on 2025-09-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refill',
            name='handled_by',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
