# Generated by Django 3.2 on 2025-09-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_refill_handled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='phone',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
