# Generated by Django 3.2 on 2025-09-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_refill_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnitems',
            name='admin_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='grnitems',
            name='site_comment',
            field=models.TextField(null=True),
        ),
    ]
