# Generated by Django 3.2 on 2025-09-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250919_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='capacity_kg',
            field=models.FloatField(null=True),
        ),
    ]
