# Generated by Django 3.2 on 2025-09-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cylinder_capacity_kg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cylinder',
            old_name='capacity_kg',
            new_name='quantity_kg',
        ),
    ]
