# Generated by Django 3.2 on 2025-09-19 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_capacity_kg_cylinder_quantity_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refill',
            name='cylinder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refills', to='core.cylinder'),
        ),
    ]
