# Generated by Django 3.2 on 2025-09-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_refill_cylinder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refill',
            name='quantity_kg',
            field=models.FloatField(null=True),
        ),
    ]
