# Generated by Django 3.2 on 2025-09-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_refill_quantity_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refill',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
