# Generated by Django 3.2 on 2025-09-19 21:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_refill_quantity_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grn',
            name='grn_Id',
            field=models.CharField(default=uuid.uuid4, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='refill',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
