# Generated by Django 3.2 on 2025-09-19 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20250919_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnitems',
            name='item_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
