# Generated by Django 3.2 on 2025-09-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_grnitems_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grnitems',
            name='item_Id',
        ),
        migrations.AddField(
            model_name='grnitems',
            name='item_id',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
