# Generated by Django 3.2 on 2025-09-19 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20250920_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grn',
            name='made_date',
        ),
        migrations.RemoveField(
            model_name='grnitems',
            name='added_date',
        ),
    ]
