# Generated by Django 3.2 on 2025-09-20 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20250920_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='made_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='grnitems',
            name='added_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
