# Generated by Django 3.2 on 2025-09-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20250920_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr/grn/'),
        ),
    ]
