# Generated by Django 3.2 on 2025-09-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_grn_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='more_info',
            field=models.TextField(null=True),
        ),
    ]
