# Generated by Django 3.2 on 2025-09-20 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_product_more_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnitems',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grn_items', to='core.product'),
        ),
    ]
