# Generated by Django 3.2 on 2025-09-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_grnitems_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnitems',
            name='item_id',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
