# Generated by Django 3.2 on 2025-09-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_grnitems_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
