# Generated by Django 3.2 on 2025-09-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_closeofdayotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size_kg',
            field=models.PositiveIntegerField(choices=[(3, '3kg'), (5, '5kg'), (10, '10kg'), (14, '14kg'), (20, '20kg'), (25, '25kg'), (30, '30kg'), (40, '40kg'), (45, '45kg'), (48, '48kg'), (50, '50kg'), (60, '60kg')]),
        ),
    ]
