# Generated by Django 3.2 on 2025-09-26 09:14

from django.db import migrations, models
import lpg_station.functions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_item_size_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='sku',
            field=models.CharField(default=lpg_station.functions.generate_cylinder_sku, max_length=30),
        ),
    ]
