# Generated by Django 3.2 on 2025-10-07 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_cylinder_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grnitems',
            name='item_id',
        ),
        migrations.AddField(
            model_name='grnitems',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grn_items', to='core.item'),
        ),
        migrations.AddField(
            model_name='grnitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grn_products', to='core.product'),
        ),
        migrations.AlterField(
            model_name='grnitems',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.grn'),
        ),
    ]
