# Generated by Django 3.2 on 2025-10-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20251007_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='assigned_site',
            field=models.TextField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='grn',
            name='rec_by',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
