# Generated by Django 3.2 on 2025-10-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20251007_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grn',
            name='assigned_site',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
