# Generated by Django 3.2 on 2025-10-07 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_grn_assigned_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grn',
            name='assigned_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.container'),
        ),
    ]
