# Generated by Django 3.2 on 2025-10-08 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_alter_grn_assigned_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closeofdayotp',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='closeofdayotp',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='closeofdayotp',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='closeofdayotp',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='closeofdayotp',
            name='total_transactions',
        ),
        migrations.AddField(
            model_name='closeofdayotp',
            name='user',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='closeofdayotp',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.CreateModel(
            name='CloseOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_refills', models.PositiveIntegerField(default=0)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
