# Generated by Django 3.2 on 2025-10-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20251008_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloseOfDayOTP',
        ),
        migrations.RenameField(
            model_name='closeofday',
            old_name='created_at',
            new_name='date_closed',
        ),
        migrations.RemoveField(
            model_name='closeofday',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='closeofday',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='closeofday',
            name='approved_by',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='closeofday',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='closeofday',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='closeofday',
            name='requested_by',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='closeofday',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='closeofday',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='closeofday',
            name='total_refills',
            field=models.IntegerField(default=0),
        ),
    ]
