# Generated by Django 3.2 on 2025-10-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20251008_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='closeofday',
            name='site_id',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
