# Generated by Django 3.2 on 2025-10-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_closeofday_site_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size_kg',
            field=models.PositiveIntegerField(choices=[(3, '3kg'), (5, '5kg'), (10, '10kg'), (14, '14kg'), (20, '20kg'), (25, '25kg'), (30, '30kg'), (35, '35kg'), (38, '38kg'), (40, '40kg'), (45, '45kg'), (48, '48kg'), (50, '50kg'), (60, '60kg')]),
        ),
    ]
