# Generated by Django 3.2 on 2025-10-14 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_item_size_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_id',
            field=models.CharField(default=uuid.uuid4, max_length=90),
        ),
    ]
