# Generated by Django 3.2 on 2025-10-15 07:36

import core.models
from django.db import migrations, models
import django.db.models.deletion
import lpg_station.functions
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_product_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurables',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code', models.ImageField(blank=True, upload_to=core.models.product_qr_upload_path)),
                ('status', models.CharField(choices=[('full', 'Full'), ('empty', 'Empty'), ('in_use', 'In-Use'), ('with_customer', 'With Customer'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='full', max_length=20)),
                ('quantity_mtrs', models.FloatField(null=True)),
                ('assigned_state', models.CharField(default=0, max_length=3)),
                ('sku', models.CharField(default=lpg_station.functions.generate_cylinder_sku, max_length=30)),
                ('location', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductQR',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code', models.ImageField(blank=True, upload_to=core.models.product_qr_upload_path)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumerSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_mtrs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_price_per_mtr', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('handled_by', models.CharField(max_length=90, null=True)),
                ('sale_id', models.CharField(default=lpg_station.functions.gen64Id, max_length=90)),
                ('qrcode', models.TextField(null=True)),
                ('site_id', models.CharField(max_length=90, null=True)),
                ('measurable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurables', to='core.measurables')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
