# Generated by Django 3.2 on 2025-10-15 07:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_consumersales_measurables_productqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=core.models.product_qr_upload_path),
        ),
    ]
