# Generated by Django 3.2 on 2025-10-17 13:27

from django.db import migrations, models
import django.db.models.deletion
import lpg_station.functions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_item_size_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='closeofday',
            name='total_sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='containerstock',
            name='sell_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='refill',
            name='isPaid',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='size_kg',
            field=models.PositiveIntegerField(choices=[(3, '3kg'), (5, '5kg'), (10, '10kg'), (14, '14kg'), (20, '20kg'), (25, '25kg'), (30, '30kg'), (40, '40kg'), (45, '45kg'), (48, '48kg'), (50, '50kg'), (60, '60kg')]),
        ),
        migrations.CreateModel(
            name='ContainerSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_id', models.CharField(default=lpg_station.functions.gen64Id, max_length=90)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sold_by', models.CharField(max_length=90)),
                ('status', models.CharField(default=0, max_length=3)),
                ('sell_type', models.CharField(blank=True, max_length=20)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='containersale', to='core.container')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='containersale', to='core.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
