# Generated by Django 3.2 on 2025-10-23 07:58

from django.db import migrations, models
import django.db.models.deletion
import lpg_station.functions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20251023_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_id', models.CharField(default=lpg_station.functions.gen64Id, max_length=90)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sold_by', models.CharField(max_length=90)),
                ('status', models.CharField(default=0, max_length=3)),
                ('sell_type', models.CharField(blank=True, max_length=20)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='containersale', to='core.container')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='containersale', to='core.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
